# Default configuration--- 
:version: 0.1.5
:directory: /tmp/traq_test
:ignore: 24
:user: taq
:list: 
- Rakefile
- config.ru
- Gemfile
- package.json
- babel.config.js
- postcss.config.js
- - config/application.rb
- - config/environment.rb
- - config/initializers/**/*
- - config/environments/production.rb
- - config/locales/**/*
- - config/routes.rb
- - config/storage.yml
- - config/webpacker.yml
- - config/webpack/environment.js
- - config/webpack/production.js
- - app/**/*
- - db/migrate/**/*
- - public/javascripts/**/*
- - public/stylesheets/**/*
- - public/404.html
- - public/422.html
- - public/500.html
- - public/favicon.ico
- - public/robots.txt
- - lib/**/*
- - public/images/**/*
  - public/images/uploads/**/*
:password: fill your password here
:host: localhost
:server: passenger
:shell: bash -l -c 
